services:
  - type: web
    name: jtb-api-gateway
    env: docker
    plan: starter
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - fromGroup: jtb-prod
      - key: PORT
        value: "8080"
    dockerfilePath: services/api-gateway/Dockerfile

  - type: web
    name: jtb-frontend
    env: docker
    plan: starter
    autoDeploy: true
    envVars:
      - fromGroup: jtb-prod
      - key: PORT
        value: "3000"
      # Imposta dopo il primo deploy dell'API:
      # - NEXT_PUBLIC_API_URL = https://<url-di-jtb-api-gateway>
    dockerfilePath: frontend/Dockerfile

  - type: worker
    name: jtb-connectors-wkr
    env: docker
    plan: starter
    autoDeploy: true
    envVars:
      - fromGroup: jtb-prod
    dockerfilePath: services/connectors-wkr/Dockerfile

  - type: worker
    name: jtb-pricing-svc
    env: docker
    plan: starter
    autoDeploy: true
    envVars:
      - fromGroup: jtb-prod
      # Nessun RUN_MODE → default "loop" dal Dockerfile
    dockerfilePath: services/pricing-svc/Dockerfile

  - type: cron
    name: jtb-cron-recompute
    env: docker
    schedule: "*/30 * * * *" # ogni 30 minuti
    dockerfilePath: services/pricing-svc/Dockerfile
    envVars:
      - fromGroup: jtb-prod
      - key: RUN_MODE
        value: "recompute"
