services:
  - type: web
    name: jtb-api-gateway
    env: docker
    plan: starter
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: "8080"
      # Imposta in Render un Environment Group con:
      # - DATABASE_URL (Postgres Internal URL)
      # - INIT_TOKEN  (stringa a tua scelta)
      # poi collegalo al servizio dalla UI
    dockerfilePath: services/api-gateway/Dockerfile

  - type: web
    name: jtb-frontend
    env: docker
    plan: starter
    autoDeploy: true
    envVars:
      - key: PORT
        value: "3000"
      # Dopo che l'API è live, aggiungi nella UI:
      # - NEXT_PUBLIC_API_URL = https://<url-di-jtb-api-gateway>
    dockerfilePath: frontend/Dockerfile

  - type: worker
    name: jtb-connectors-wkr
    env: docker
    plan: starter
    autoDeploy: true
    envVars: []
    dockerfilePath: services/connectors-wkr/Dockerfile

  - type: worker
    name: jtb-pricing-svc
    env: docker
    plan: starter
    autoDeploy: true
    envVars: []
    dockerfilePath: services/pricing-svc/Dockerfile

  - type: cron
    name: jtb-cron-recompute
    env: docker
    schedule: "*/30 * * * *" # ogni 30 minuti
    dockerfilePath: services/pricing-svc/Dockerfile
    startCommand: bash -lc "python -m app.tasks recompute"

